/**
 * AGENTS.md Writer
 *
 * Generates AGENTS.md from GPT analysis with stable output.
 */

import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import chalk from 'chalk';

export interface WriteOptions {
  dryRun?: boolean;
  preserveCustom?: boolean;  // Keep user-added sections
}

const HEADER = `# AGENTS.md

> Auto-generated by [Auracoil](https://github.com/your-org/auracoil) using GPT 5.2 Pro analysis.
> Last updated: {{DATE}}

This documentation helps AI coding assistants (Claude Code, Codex CLI) work effectively with this codebase.

---

`;

const FOOTER = `
---

## Contributing to This Doc

This file is generated by Auracoil. To update:
1. Run \`auracoil update\` to refresh from codebase changes
2. For custom sections, add them between \`<!-- custom:start -->\` and \`<!-- custom:end -->\` markers

<!-- custom:start -->
<!-- Add your custom content here - it will be preserved during updates -->
<!-- custom:end -->
`;

/**
 * Write AGENTS.md from analysis content
 */
export async function writeAgentsMd(
  repoPath: string,
  analysisContent: string,
  options: WriteOptions = {}
): Promise<{ written: boolean; path: string; content: string }> {
  const agentsPath = join(repoPath, 'AGENTS.md');
  const date = new Date().toISOString().split('T')[0];

  // Build content
  let content = HEADER.replace('{{DATE}}', date);
  content += analysisContent;
  content += FOOTER;

  // Preserve custom sections if updating
  if (options.preserveCustom) {
    try {
      const existing = await readFile(agentsPath, 'utf-8');
      const customContent = extractCustomSection(existing);
      if (customContent) {
        content = content.replace(
          /<!-- custom:start -->[\s\S]*<!-- custom:end -->/,
          `<!-- custom:start -->\n${customContent}\n<!-- custom:end -->`
        );
      }
    } catch {
      // No existing file
    }
  }

  if (options.dryRun) {
    console.log(chalk.dim('\n  [Dry run] Would write AGENTS.md:'));
    console.log(chalk.dim('  ' + '-'.repeat(50)));
    // Show first 50 lines
    const lines = content.split('\n').slice(0, 50);
    for (const line of lines) {
      console.log(chalk.dim(`  ${line}`));
    }
    if (content.split('\n').length > 50) {
      console.log(chalk.dim('  ... (truncated)'));
    }
    console.log(chalk.dim('  ' + '-'.repeat(50)));

    return { written: false, path: agentsPath, content };
  }

  await writeFile(agentsPath, content);
  console.log(chalk.green(`  ✓ Written ${agentsPath}`));

  return { written: true, path: agentsPath, content };
}

/**
 * Extract custom section from existing AGENTS.md
 */
function extractCustomSection(content: string): string | null {
  const startMarker = '<!-- custom:start -->';
  const endMarker = '<!-- custom:end -->';

  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) {
    return null;
  }

  const customContent = content
    .substring(startIdx + startMarker.length, endIdx)
    .trim();

  // Return null if it's just the placeholder comment
  if (customContent.includes('Add your custom content here')) {
    return null;
  }

  return customContent || null;
}

/**
 * Check if AGENTS.md would change
 */
export async function wouldChange(
  repoPath: string,
  newContent: string
): Promise<boolean> {
  const agentsPath = join(repoPath, 'AGENTS.md');

  try {
    const existing = await readFile(agentsPath, 'utf-8');

    // Normalize for comparison (ignore date changes)
    const normalizedExisting = normalizeForComparison(existing);
    const normalizedNew = normalizeForComparison(newContent);

    return normalizedExisting !== normalizedNew;
  } catch {
    // File doesn't exist, would change
    return true;
  }
}

/**
 * Normalize content for comparison
 */
function normalizeForComparison(content: string): string {
  return content
    // Remove date line
    .replace(/Last updated: \d{4}-\d{2}-\d{2}/, 'Last updated: DATE')
    // Normalize whitespace
    .replace(/\r\n/g, '\n')
    .replace(/\n\n\n+/g, '\n\n')
    .trim();
}
